-- OUTPUT FORMAT
OutputBoard ::= SEQUENCE {
  size INTEGER, -- assuming same width and height, as this is the case in the examples
  horizontalSegments SEQUENCE OF BOOLEAN, -- rows, from left to right
  verticalSegments SEQUENCE OF BOOLEAN -- columns, from top to bottom
}

sample5x5 OutputBoard ::= {
  size 5,
  horizontalSegments {
    TRUE,  TRUE,  TRUE,  TRUE,  TRUE,
    TRUE,  TRUE,  TRUE,  FALSE, FALSE,
    TRUE,  FALSE, TRUE,  FALSE, TRUE,
    FALSE, TRUE,  FALSE, TRUE,  FALSE,
    FALSE, TRUE,  FALSE, TRUE,  TRUE,
    TRUE,  FALSE, TRUE,  TRUE,  TRUE
  },
  verticalSegments {
    TRUE,  FALSE, TRUE,  TRUE,  TRUE,
    FALSE, FALSE, TRUE,  FALSE, TRUE,
    FALSE, FALSE, TRUE,  FALSE, TRUE,
    FALSE, TRUE,  FALSE, TRUE,  FALSE,
    FALSE, FALSE, TRUE,  FALSE, FALSE,
    TRUE,  TRUE,  FALSE, FALSE, TRUE
  }
}
